### ISSUE TITLE
missing support for multi file download

### ISSUE THREAD

**Issue by patrick-griffiths** [Open-EO/openeo-web-editor#308] opened 2023-07-17 00:20 UTC
@m-mohr et al. 

it would be great to support the download of many result files from the editor. 
Currently each file download has to be individually initiated on click....

![image](https://github.com/Open-EO/openeo-web-editor/assets/40148967/bde83b91-9056-4447-91a9-5d28fee8fe24)

**Comment by m-mohr** [comment] 2023-07-17 08:42
Duplicate of #268

**Closed** 2023-07-17 08:42 UTC
