### ISSUE TITLE
Job panel (queuing job): Cannot read property 'jobId' of undefined

### ISSUE THREAD

**Issue by Sijoma** [Open-EO/openeo-web-editor#28] opened 2019-03-16 12:25 UTC
Queuing job a batch job seems to work (status is displayed as finished after a short period of time). However, it returns the following error.

![image](https://user-images.githubusercontent.com/8970764/54475185-b53d6900-47ee-11e9-86c9-7d307538cac0.png)

TypeError: Cannot read property 'jobId' of undefined
    at JobPanel.vue:166
    at Array.findIndex (<anonymous>)
    at a.updateJobData (JobPanel.vue:166)
    at JobPanel.vue:231

Additional info to reproduce:

Process graph:

```
{
  "imagery": {
    "red": "B4",
    "nir": "B8A",
    "imagery": {
      "extent": [
        "2018-01-01T00:00:00Z",
        "2018-12-31T23:59:59Z"
      ],
      "imagery": {
        "extent": {
          "west": 4.757069,
          "south": 51.502332,
          "east": 6.020497,
          "north": 52.849645
        },
        "imagery": {
          "process_id": "get_collection",
          "name": "COPERNICUS/S2"
        },
        "process_id": "filter_bbox"
      },
      "process_id": "filter_daterange"
    },
    "process_id": "NDVI"
  },
  "process_id": "sum_time"
}
```

**Comment by m-mohr** [comment] 2019-03-16 12:28
Which back-end are you working with? GEE?

**Comment by Sijoma** [comment] 2019-03-16 12:29
Yes GEE. https://earthengine.openeo.org/v0.3

**Comment by Sijoma** [comment] 2019-03-16 12:40
The results are also correctly retrieved. So I think this is just a minor issue with the variable job id not being propagated correctly. The same error also occurs when I click on Job details, even though the ID is also displayed there.

**Comment by m-mohr** [comment] 2019-03-19 11:33
I can't reproduce it, maybe it was fixed in the meantime. Can you try it again on https://editor.openeo.org ?

**Comment by m-mohr** [comment] 2019-03-19 12:42
It seems I found the bug: 
`delete this.watchers[index];` => `this.watchers.splice(index, 1);`
Delete just sets an array element to undefined, but doesn't return it.

**Closed by m-mohr** 2019-03-19 12:42 UTC
Labels: bug
